### ISSUE TITLE
PNG to PNG asset conversion should use hard links instead of duplicating data

### ISSUE THREAD

**Issue by turecross321** [jvyden/jvyden#1]
Please Fix...

**Comment by jvyden** [comment]
for sure

**Comment by jvyden** [comment]
This is getting a little out of control, guys. Keep it chill.

**Comment by jvyden** [comment]
You'll never even have a chance at doing this, Turecross321.

**Comment by turecross321** [comment]
Unbelievable... I will talk to Steve about this.

**Comment by turecross321** [comment]
Steve will be contacted if I'm not reassigned.

**Comment by turecross321** [comment]
I will let Steve know about this.

**Comment by jvyden** [comment]
Steve? Really? Get a grip.

**Comment by turecross321** [comment]
You can fix this before I tell Steve.

**Comment by jvyden** [comment]
Get a hold of it.

**Comment by jvyden** [comment]
I will tell Steve if you tell Steve.

**Comment by jvyden** [comment]
You don't wanna mess with Steve.

**Comment by turecross321** [comment]
**Steve will not be happy, bro.**

**Comment by jvyden** [comment]
![image](https://github.com/user-attachments/assets/58061e20-3512-4a91-be0d-0419986ca0ea)
You've done it now.

**Comment by jvyden** [comment]
How did I do today? :)

# [:smile:](https://www.youtube.com/watch?v=sTSA_sWGM44) [:expressionless:](https://www.youtube.com/watch?v=sTSA_sWGM44) [:cry:](https://www.youtube.com/watch?v=sTSA_sWGM44)
